### ISSUE TITLE
Para üstü alma sorunu!

### ISSUE THREAD

**Issue by ahsentekd** [tygrysco/avdobakkal#2]
avdo bakkal uygulmasında para üstünü anında alıyoruz fakat gerçekte para üstünü hesap makinasında yaklaşık 1 dakika geçikmeyle hesaplaması sonucunda veriyor lütfen fixler misin

**Comment by hasanpolatt** [comment]
İsteğiniz dikkate alınmıştır. En kısa zamanda düzeltilecektir.
